// ============================================================
// 단어 데이터 파일
// ============================================================
// 새 시험을 추가하려면: 아래 VOCAB_DATA 객체에 새로운
// 최상위 키(예: "2026년 6월")를 추가하고, 그 안에 지문 번호별로
// 단어 배열을 넣으면 됩니다.
//
// 각 단어는 이 형식을 따릅니다:
//   { word: "영단어", meaning: "정답 뜻", distractors: ["오답1", "오답2"] }
//
// distractors(오답 보기)는 정확히 2개를 넣어주세요.
// 정답 1개 + 오답 2개 = 3지선다 문제가 만들어집니다.
//
// 예시: 새로운 지문(예: 50번)을 추가하려면
//   50: [
//     { word: "example", meaning: "예시", distractors: ["결과", "원인"] },
//     ...
//   ],
// 이렇게 같은 시험 객체 안에 추가하면 됩니다.
// ============================================================

const VOCAB_DATA = {
  "2026년 3월": {
    18: [
      { word: "appreciate", meaning: "감사하다", distractors: ["사과하다", "비판하다"] },
      { word: "continued", meaning: "지속적인", distractors: ["일시적인", "간헐적인"] },
      { word: "conducting", meaning: "수행하는", distractors: ["포기하는", "방해하는"] },
      { word: "essential", meaning: "필수적인", distractors: ["선택적인", "부수적인"] },
      { word: "maintenance", meaning: "유지 보수", distractors: ["건설", "철거"] },
      { word: "underground", meaning: "지하의", distractors: ["지상의", "해상의"] },
      { word: "facility", meaning: "시설", distractors: ["장애물", "규정"] },
      { word: "unavailable", meaning: "이용할 수 없는", distractors: ["이용 가능한", "예약된"] },
      { word: "period", meaning: "기간", distractors: ["장소", "목적"] },
      { word: "temporary", meaning: "임시의", distractors: ["영구적인", "정기적인"] },
      { word: "outdoor", meaning: "옥외의", distractors: ["실내의", "지하의"] },
      { word: "entrance", meaning: "입구", distractors: ["출구", "창문"] },
      { word: "committed", meaning: "전념하는", distractors: ["포기하는", "망설이는"] },
      { word: "inconvenience", meaning: "불편", distractors: ["편의", "혜택"] },
      { word: "cooperation", meaning: "협조", distractors: ["경쟁", "갈등"] },
    ],
    19: [
      { word: "cafeteria", meaning: "구내식당", distractors: ["도서관", "강당"] },
      { word: "gripped", meaning: "꽉 잡았다", distractors: ["가볍게 놓았다", "내던졌다"] },
      { word: "tray", meaning: "쟁반", distractors: ["냄비", "바구니"] },
      { word: "anxious", meaning: "불안한", distractors: ["평온한", "자신감 있는"] },
      { word: "sigh", meaning: "한숨", distractors: ["웃음", "고함"] },
      { word: "opposite", meaning: "맞은편의", distractors: ["같은 편의", "위쪽의"] },
      { word: "lending", meaning: "빌려주기", distractors: ["빌리기", "구매하기"] },
      { word: "invisible", meaning: "보이지 않는", distractors: ["눈에 띄는", "투명한"] },
      { word: "wall", meaning: "벽", distractors: ["천장", "바닥"] },
      { word: "melt", meaning: "녹다", distractors: ["굳다", "얼다"] },
      { word: "replied", meaning: "대답했다", distractors: ["무시했다", "질문했다"] },
      { word: "starting", meaning: "시작하는", distractors: ["끝내는", "멈추는"] },
      { word: "ease", meaning: "편안함", distractors: ["긴장감", "불쾌함"] },
      { word: "smiled", meaning: "미소 지었다", distractors: ["찡그렸다", "울었다"] },
      { word: "brightly", meaning: "밝게", distractors: ["어둡게", "조용히"] },
    ],
    20: [
      { word: "situation", meaning: "상황", distractors: ["결과", "원인"] },
      { word: "master", meaning: "통달하다", distractors: ["포기하다", "회피하다"] },
      { word: "connections", meaning: "연결", distractors: ["단절", "분리"] },
      { word: "distract", meaning: "주의를 분산시키다", distractors: ["집중시키다", "안정시키다"] },
      { word: "mistake", meaning: "실수", distractors: ["성공", "성취"] },
      { word: "unidimensional", meaning: "일차원적인", distractors: ["다차원적인", "복잡한"] },
      { word: "remedies", meaning: "해결책", distractors: ["문제점", "장애물"] },
      { word: "inevitably", meaning: "불가피하게", distractors: ["선택적으로", "우연히"] },
      { word: "bombarding", meaning: "퍼붓는", distractors: ["차단하는", "흡수하는"] },
      { word: "transition", meaning: "전환기", distractors: ["안정기", "퇴보기"] },
      { word: "counterbalance", meaning: "균형을 맞추다", distractors: ["무너뜨리다", "강화하다"] },
      { word: "stress", meaning: "스트레스", distractors: ["여유", "안정"] },
      { word: "laserfocused", meaning: "매우 집중한", distractors: ["산만한", "무관심한"] },
      { word: "networks", meaning: "네트워크", distractors: ["고립", "단절"] },
      { word: "shape", meaning: "형성하다", distractors: ["파괴하다", "방치하다"] },
    ],
    21: [
      { word: "establishing", meaning: "확립하는", distractors: ["무너뜨리는", "의심하는"] },
      { word: "respectful", meaning: "존중하는", distractors: ["무시하는", "비하하는"] },
      { word: "acceptance", meaning: "수용", distractors: ["거절", "무시"] },
      { word: "regardless", meaning: "상관없이", distractors: ["관련하여", "때문에"] },
      { word: "obvious", meaning: "명백한", distractors: ["불분명한", "모호한"] },
      { word: "mathematical", meaning: "수학적인", distractors: ["문학적인", "역사적인"] },
      { word: "discussions", meaning: "토론", distractors: ["독백", "침묵"] },
      { word: "misconceptions", meaning: "오해", distractors: ["정확한 이해", "직관"] },
      { word: "forefront", meaning: "최전선", distractors: ["후방", "중립 지대"] },
      { word: "confront", meaning: "직면하다", distractors: ["회피하다", "무시하다"] },
      { word: "willing", meaning: "기꺼이 ~하는", distractors: ["거부하는", "망설이는"] },
      { word: "derogatory", meaning: "비하하는", distractors: ["칭찬하는", "존중하는"] },
      { word: "expressions", meaning: "표현", distractors: ["침묵", "억압"] },
      { word: "equipping", meaning: "준비시키는", distractors: ["무장 해제시키는", "방치하는"] },
      { word: "solutions", meaning: "해결책", distractors: ["문제", "장애물"] },
    ],
    22: [
      { word: "intercity", meaning: "도시 간의", distractors: ["도시 내의", "국제적인"] },
      { word: "traveler", meaning: "여행객", distractors: ["거주민", "직원"] },
      { word: "passenger", meaning: "승객", distractors: ["운전자", "안내원"] },
      { word: "familiar", meaning: "익숙한", distractors: ["낯선", "어색한"] },
      { word: "baggage", meaning: "짐", distractors: ["좌석", "티켓"] },
      { word: "connections", meaning: "연결편", distractors: ["출발편", "종착편"] },
      { word: "commuters", meaning: "통근자", distractors: ["여행자", "관광객"] },
      { word: "luggage", meaning: "수하물", distractors: ["기내식", "탑승권"] },
      { word: "access", meaning: "접근", distractors: ["차단", "거절"] },
      { word: "transport", meaning: "교통", distractors: ["숙박", "관광"] },
      { word: "separate", meaning: "분리하다", distractors: ["연결하다", "통합하다"] },
      { word: "conflict", meaning: "충돌", distractors: ["협력", "조화"] },
      { word: "confusion", meaning: "혼란", distractors: ["명확함", "질서"] },
      { word: "platforms", meaning: "승강장", distractors: ["매표소", "대기실"] },
      { word: "channelization", meaning: "수로화", distractors: ["분산화", "통합화"] },
    ],
    23: [
      { word: "performance", meaning: "공연", distractors: ["연습", "감상"] },
      { word: "lighting", meaning: "조명", distractors: ["음향", "무대 장치"] },
      { word: "states", meaning: "상태", distractors: ["변화", "결과"] },
      { word: "cue", meaning: "신호", distractors: ["방해", "소음"] },
      { word: "triggers", meaning: "유발하다", distractors: ["억제하다", "차단하다"] },
      { word: "motivation", meaning: "동기", distractors: ["결과", "결론"] },
      { word: "brighten", meaning: "밝게 하다", distractors: ["어둡게 하다", "흐리게 하다"] },
      { word: "intensity", meaning: "강도", distractors: ["빈도", "방향"] },
      { word: "traditional", meaning: "전통적인", distractors: ["현대적인", "실험적인"] },
      { word: "subtle", meaning: "미묘한", distractors: ["명백한", "강렬한"] },
      { word: "atmosphere", meaning: "분위기", distractors: ["조명", "음향"] },
      { word: "threaten", meaning: "위협하다", distractors: ["보호하다", "격려하다"] },
      { word: "production", meaning: "제작", distractors: ["감상", "비평"] },
      { word: "dramatic", meaning: "극적인", distractors: ["평범한", "단조로운"] },
      { word: "transition", meaning: "전환", distractors: ["반복", "중단"] },
    ],
    24: [
      { word: "impose", meaning: "부과하다", distractors: ["면제하다", "허용하다"] },
      { word: "characteristics", meaning: "특성", distractors: ["결함", "공통점"] },
      { word: "audio", meaning: "오디오의", distractors: ["시각의", "촉각의"] },
      { word: "remarkable", meaning: "놀라운", distractors: ["평범한", "실망스러운"] },
      { word: "headphones", meaning: "헤드폰", distractors: ["마이크", "스피커"] },
      { word: "acoustical", meaning: "음향의", distractors: ["시각적인", "전기적인"] },
      { word: "playback", meaning: "재생", distractors: ["녹음", "편집"] },
      { word: "loudspeaker", meaning: "확성기", distractors: ["수신기", "변환기"] },
      { word: "dramatically", meaning: "극적으로", distractors: ["서서히", "평범하게"] },
      { word: "signal", meaning: "신호", distractors: ["소음", "침묵"] },
      { word: "locations", meaning: "위치", distractors: ["방향", "거리"] },
      { word: "recording", meaning: "녹음", distractors: ["재생", "편집"] },
      { word: "instrument", meaning: "악기", distractors: ["의상", "무대"] },
      { word: "microphone", meaning: "마이크", distractors: ["헤드폰", "앰프"] },
      { word: "transmission", meaning: "전송", distractors: ["수신", "저장"] },
    ],
    25: [
      { word: "percentages", meaning: "백분율", distractors: ["절대값", "평균"] },
      { word: "consumers", meaning: "소비자", distractors: ["생산자", "공급자"] },
      { word: "likely", meaning: "할 것 같은", distractors: ["불가능한", "불확실한"] },
      { word: "respond", meaning: "응답하다", distractors: ["무시하다", "질문하다"] },
      { word: "review", meaning: "검토/후기", distractors: ["무시", "삭제"] },
      { word: "methods", meaning: "방법", distractors: ["결과", "목표"] },
      { word: "graph", meaning: "그래프", distractors: ["표", "목록"] },
      { word: "email", meaning: "이메일", distractors: ["전화", "문자"] },
      { word: "highest", meaning: "가장 높은", distractors: ["가장 낮은", "평균적인"] },
      { word: "person", meaning: "사람/직접", distractors: ["기계", "온라인"] },
      { word: "social", meaning: "사회적인", distractors: ["개인적인", "경제적인"] },
      { word: "media", meaning: "매체", distractors: ["내용", "전달자"] },
      { word: "gap", meaning: "격차", distractors: ["평등", "일치"] },
      { word: "smaller", meaning: "더 작은", distractors: ["더 큰", "동일한"] },
      { word: "text", meaning: "문자", distractors: ["이미지", "영상"] },
    ],
    26: [
      { word: "born", meaning: "태어난", distractors: ["성장한", "사망한"] },
      { word: "education", meaning: "교육", distractors: ["경험", "재능"] },
      { word: "mathematics", meaning: "수학", distractors: ["물리학", "화학"] },
      { word: "physics", meaning: "물리학", distractors: ["생물학", "수학"] },
      { word: "doctoral", meaning: "박사의", distractors: ["학사의", "석사의"] },
      { word: "university", meaning: "대학교", distractors: ["고등학교", "연구소"] },
      { word: "famous", meaning: "유명한", distractors: ["무명의", "평범한"] },
      { word: "research", meaning: "연구", distractors: ["발표", "적용"] },
      { word: "universe", meaning: "우주", distractors: ["지구", "태양계"] },
      { word: "theory", meaning: "이론", distractors: ["실험", "증거"] },
      { word: "evidence", meaning: "증거", distractors: ["가설", "추측"] },
      { word: "model", meaning: "모델", distractors: ["공식", "법칙"] },
      { word: "awarded", meaning: "수여된", distractors: ["박탈된", "지원된"] },
      { word: "contributions", meaning: "기여", distractors: ["방해", "무관심"] },
      { word: "mentor", meaning: "멘토", distractors: ["경쟁자", "제자"] },
    ],
    29: [
      { word: "Industrial", meaning: "산업의", distractors: ["농업의", "상업의"] },
      { word: "Revolution", meaning: "혁명", distractors: ["진화", "발전"] },
      { word: "invent", meaning: "발명하다", distractors: ["모방하다", "폐기하다"] },
      { word: "materials", meaning: "재료", distractors: ["도구", "설비"] },
      { word: "manufacturing", meaning: "제조", distractors: ["판매", "유통"] },
      { word: "factory", meaning: "공장", distractors: ["창고", "사무실"] },
      { word: "apprentice", meaning: "견습생", distractors: ["전문가", "관리자"] },
      { word: "builder", meaning: "건축가", distractors: ["설계자", "감독관"] },
      { word: "specialists", meaning: "전문가", distractors: ["초보자", "견습생"] },
      { word: "produced", meaning: "생산했다", distractors: ["소비했다", "폐기했다"] },
      { word: "development", meaning: "발달", distractors: ["퇴보", "유지"] },
      { word: "efficiency", meaning: "효율성", distractors: ["비효율성", "생산량"] },
      { word: "quality", meaning: "품질", distractors: ["수량", "가격"] },
      { word: "casting", meaning: "주조", distractors: ["절단", "조립"] },
      { word: "facility", meaning: "시설", distractors: ["제품", "인력"] },
    ],
    30: [
      { word: "thesisbased", meaning: "논문 기반의", distractors: ["실험 기반의", "강의 기반의"] },
      { word: "doctoral", meaning: "박사의", distractors: ["학사의", "석사의"] },
      { word: "programme", meaning: "프로그램", distractors: ["커리큘럼", "강의"] },
      { word: "researching", meaning: "연구하는", distractors: ["발표하는", "적용하는"] },
      { word: "exploration", meaning: "탐구", distractors: ["결론", "증명"] },
      { word: "narrowing", meaning: "좁히는", distractors: ["넓히는", "유지하는"] },
      { word: "absorbed", meaning: "몰두한", distractors: ["무관심한", "분산된"] },
      { word: "limit", meaning: "제한하다", distractors: ["확장하다", "허용하다"] },
      { word: "breadth", meaning: "폭", distractors: ["깊이", "높이"] },
      { word: "knowledge", meaning: "지식", distractors: ["기술", "경험"] },
      { word: "adapt", meaning: "적응하다", distractors: ["저항하다", "무시하다"] },
      { word: "interdisciplinary", meaning: "학제간의", distractors: ["단일 학문의", "전문적인"] },
      { word: "structured", meaning: "구조화된", distractors: ["자유로운", "무질서한"] },
      { word: "transferable", meaning: "전이 가능한", distractors: ["고정된", "제한된"] },
      { word: "curriculum", meaning: "교육과정", distractors: ["시험", "수업"] },
    ],
    31: [
      { word: "Research", meaning: "연구", distractors: ["발표", "실험"] },
      { word: "imaginary", meaning: "상상의", distractors: ["현실의", "역사적인"] },
      { word: "objects", meaning: "물체", distractors: ["개념", "감정"] },
      { word: "everyday", meaning: "일상의", distractors: ["특별한", "비일상적인"] },
      { word: "disrupt", meaning: "방해하다", distractors: ["촉진하다", "유지하다"] },
      { word: "expression", meaning: "표현", distractors: ["억압", "침묵"] },
      { word: "monsters", meaning: "괴물", distractors: ["영웅", "인간"] },
      { word: "causal", meaning: "인과적인", distractors: ["우연적인", "순환적인"] },
      { word: "relations", meaning: "관계", distractors: ["단절", "차이"] },
      { word: "reality", meaning: "현실", distractors: ["상상", "환상"] },
      { word: "pretend", meaning: "가장하다", distractors: ["인정하다", "드러내다"] },
      { word: "preschool", meaning: "미취학의", distractors: ["초등학생의", "성인의"] },
      { word: "exhibited", meaning: "보였다", distractors: ["숨겼다", "부정했다"] },
      { word: "avoidance", meaning: "회피", distractors: ["직면", "수용"] },
      { word: "emotion", meaning: "감정", distractors: ["이성", "본능"] },
    ],
    32: [
      { word: "liberation", meaning: "해방", distractors: ["억압", "구속"] },
      { word: "expansion", meaning: "확장", distractors: ["축소", "유지"] },
      { word: "aesthetic", meaning: "미학의", distractors: ["윤리의", "논리의"] },
      { word: "everyday", meaning: "일상의", distractors: ["특별한", "예외적인"] },
      { word: "gratification", meaning: "만족감", distractors: ["불만족감", "결핍감"] },
      { word: "ordinary", meaning: "평범한", distractors: ["특별한", "독특한"] },
      { word: "degraded", meaning: "가치가 떨어진", distractors: ["가치가 높아진", "인정받은"] },
      { word: "dismissed", meaning: "무시된", distractors: ["수용된", "인정된"] },
      { word: "prevalent", meaning: "널리 퍼진", distractors: ["드문", "사라진"] },
      { word: "philosophical", meaning: "철학적인", distractors: ["과학적인", "감정적인"] },
      { word: "intellectual", meaning: "지적인", distractors: ["감정적인", "육체적인"] },
      { word: "biological", meaning: "생물학적인", distractors: ["화학적인", "물리적인"] },
      { word: "cultural", meaning: "문화적인", distractors: ["자연적인", "경제적인"] },
      { word: "interpenetration", meaning: "상호 침투", distractors: ["완전한 분리", "일방적 흡수"] },
      { word: "intensified", meaning: "강화된", distractors: ["약화된", "유지된"] },
    ],
    33: [
      { word: "validly", meaning: "타당하게", distractors: ["부당하게", "임의로"] },
      { word: "morally", meaning: "도덕적으로", distractors: ["비도덕적으로", "법적으로"] },
      { word: "superior", meaning: "우월한", distractors: ["열등한", "동등한"] },
      { word: "possess", meaning: "소유하다", distractors: ["포기하다", "결여하다"] },
      { word: "capacities", meaning: "능력", distractors: ["결함", "한계"] },
      { word: "agent", meaning: "행위자", distractors: ["관찰자", "피해자"] },
      { word: "meaningfully", meaning: "의미 있게", distractors: ["무의미하게", "임의로"] },
      { word: "judged", meaning: "판단된", distractors: ["무시된", "용인된"] },
      { word: "comparative", meaning: "비교적인", distractors: ["절대적인", "독립적인"] },
      { word: "merits", meaning: "장점", distractors: ["단점", "결함"] },
      { word: "deficiencies", meaning: "결함", distractors: ["장점", "능력"] },
      { word: "entities", meaning: "존재", distractors: ["개념", "관계"] },
      { word: "determined", meaning: "결정된", distractors: ["불확실한", "변화하는"] },
      { word: "fulfills", meaning: "충족하다", distractors: ["결여하다", "초과하다"] },
      { word: "application", meaning: "적용", distractors: ["이론", "연구"] },
    ],
    34: [
      { word: "artificial", meaning: "인공적인", distractors: ["자연적인", "유기적인"] },
      { word: "supplements", meaning: "보충물", distractors: ["대체물", "장애물"] },
      { word: "cadence", meaning: "억양", distractors: ["속도", "음량"] },
      { word: "convince", meaning: "확신시키다", distractors: ["의심하게 하다", "혼란시키다"] },
      { word: "interlocutors", meaning: "대화 상대", distractors: ["청중", "관찰자"] },
      { word: "engaging", meaning: "참여하는", distractors: ["회피하는", "무시하는"] },
      { word: "humanity", meaning: "인간성", distractors: ["기계성", "동물성"] },
      { word: "emerges", meaning: "나타나다", distractors: ["사라지다", "유지되다"] },
      { word: "reinforcing", meaning: "강화하는", distractors: ["약화하는", "제거하는"] },
      { word: "illusion", meaning: "착각", distractors: ["현실", "진실"] },
      { word: "handling", meaning: "처리", distractors: ["회피", "방치"] },
      { word: "duration", meaning: "지속 시간", distractors: ["빈도", "강도"] },
      { word: "frequency", meaning: "빈도", distractors: ["강도", "기간"] },
      { word: "significant", meaning: "상당한", distractors: ["미미한", "무의미한"] },
      { word: "context", meaning: "맥락", distractors: ["결론", "주제"] },
    ],
    35: [
      { word: "standardization", meaning: "표준화", distractors: ["개별화", "다양화"] },
      { word: "printing", meaning: "인쇄", distractors: ["필사", "복사"] },
      { word: "exact", meaning: "정확한", distractors: ["부정확한", "모호한"] },
      { word: "reproduction", meaning: "복제", distractors: ["창작", "파괴"] },
      { word: "manuscript", meaning: "필사본", distractors: ["인쇄본", "전자책"] },
      { word: "evident", meaning: "분명한", distractors: ["불분명한", "숨겨진"] },
      { word: "contrast", meaning: "대조", distractors: ["유사점", "일치"] },
      { word: "narrative", meaning: "이야기", distractors: ["논문", "도표"] },
      { word: "authentic", meaning: "진본의", distractors: ["가짜의", "복제된"] },
      { word: "exploration", meaning: "탐험", distractors: ["정착", "후퇴"] },
      { word: "distributed", meaning: "분배된", distractors: ["독점된", "집중된"] },
      { word: "lacking", meaning: "부족한", distractors: ["충분한", "넘치는"] },
      { word: "observation", meaning: "관찰", distractors: ["실험", "분석"] },
      { word: "novelty", meaning: "참신함", distractors: ["진부함", "전통성"] },
      { word: "accuracy", meaning: "정확성", distractors: ["모호성", "오류"] },
    ],
    36: [
      { word: "archaeological", meaning: "고고학적인", distractors: ["역사적인", "인류학적인"] },
      { word: "cultivated", meaning: "경작된", distractors: ["자연 그대로의", "황폐해진"] },
      { word: "political", meaning: "정치적인", distractors: ["경제적인", "사회적인"] },
      { word: "economic", meaning: "경제적인", distractors: ["정치적인", "문화적인"] },
      { word: "patterns", meaning: "양상", distractors: ["원인", "결과"] },
      { word: "density", meaning: "밀도", distractors: ["면적", "부피"] },
      { word: "agricultural", meaning: "농업의", distractors: ["산업의", "상업의"] },
      { word: "declining", meaning: "감소하는", distractors: ["증가하는", "유지되는"] },
      { word: "production", meaning: "생산", distractors: ["소비", "유통"] },
      { word: "projected", meaning: "예상되는", distractors: ["확인된", "포기된"] },
      { word: "demand", meaning: "수요", distractors: ["공급", "소비"] },
      { word: "limitations", meaning: "한계", distractors: ["장점", "가능성"] },
      { word: "climate", meaning: "기후", distractors: ["날씨", "지형"] },
      { word: "topography", meaning: "지형", distractors: ["기후", "식생"] },
      { word: "millennia", meaning: "수천 년", distractors: ["수백 년", "수십 년"] },
    ],
    37: [
      { word: "compare", meaning: "비교하다", distractors: ["분류하다", "설명하다"] },
      { word: "languages", meaning: "언어", distractors: ["문화", "역사"] },
      { word: "confident", meaning: "확신하는", distractors: ["의심하는", "불확실한"] },
      { word: "probability", meaning: "확률", distractors: ["가능성", "빈도"] },
      { word: "relationship", meaning: "관계", distractors: ["차이", "거리"] },
      { word: "predictable", meaning: "예측 가능한", distractors: ["예측 불가능한", "무작위적인"] },
      { word: "kinship", meaning: "친족", distractors: ["친구", "동료"] },
      { word: "terminology", meaning: "용어", distractors: ["문법", "발음"] },
      { word: "category", meaning: "범주", distractors: ["개념", "원칙"] },
      { word: "comparative", meaning: "비교의", distractors: ["절대적인", "독립적인"] },
      { word: "typological", meaning: "유형학의", distractors: ["역사적인", "비교적인"] },
      { word: "discovered", meaning: "발견했다", distractors: ["창조했다", "소멸시켰다"] },
      { word: "labels", meaning: "명칭", distractors: ["정의", "원칙"] },
      { word: "modifying", meaning: "수정하는", distractors: ["유지하는", "파괴하는"] },
      { word: "central", meaning: "중심의", distractors: ["주변의", "외부의"] },
    ],
    38: [
      { word: "participant", meaning: "참가자", distractors: ["관찰자", "주최자"] },
      { word: "communicate", meaning: "전달하다", distractors: ["차단하다", "왜곡하다"] },
      { word: "fictional", meaning: "허구의", distractors: ["실제의", "역사적인"] },
      { word: "insufficient", meaning: "불충분한", distractors: ["충분한", "풍부한"] },
      { word: "maintain", meaning: "유지하다", distractors: ["포기하다", "변경하다"] },
      { word: "common", meaning: "공통의", distractors: ["개인적인", "독특한"] },
      { word: "ground", meaning: "기반", distractors: ["결과", "목표"] },
      { word: "makebelieve", meaning: "가상 역할 놀이", distractors: ["현실 놀이", "규칙 게임"] },
      { word: "emitted", meaning: "방출된", distractors: ["흡수된", "차단된"] },
      { word: "naturally", meaning: "자연스럽게", distractors: ["인위적으로", "억지로"] },
      { word: "participation", meaning: "참여", distractors: ["관찰", "방해"] },
      { word: "gasp", meaning: "숨을 헐떡이다", distractors: ["조용히 숨쉬다", "크게 웃다"] },
      { word: "sufficient", meaning: "충분한", distractors: ["부족한", "과도한"] },
      { word: "avoid", meaning: "피하다", distractors: ["직면하다", "수용하다"] },
      { word: "confusion", meaning: "혼란", distractors: ["명확함", "이해"] },
    ],
    39: [
      { word: "intuition", meaning: "직관", distractors: ["논리", "계산"] },
      { word: "matter", meaning: "물질", distractors: ["에너지", "공간"] },
      { word: "uniformly", meaning: "균일하게", distractors: ["불균일하게", "무작위로"] },
      { word: "variations", meaning: "변화", distractors: ["일정함", "반복"] },
      { word: "temperature", meaning: "온도", distractors: ["압력", "밀도"] },
      { word: "intuitively", meaning: "직관적으로", distractors: ["논리적으로", "체계적으로"] },
      { word: "assume", meaning: "가정하다", distractors: ["증명하다", "부정하다"] },
      { word: "reflects", meaning: "반영하다", distractors: ["무시하다", "왜곡하다"] },
      { word: "bias", meaning: "편향", distractors: ["객관성", "균형"] },
      { word: "constant", meaning: "일정한", distractors: ["변화하는", "불규칙한"] },
      { word: "metabolism", meaning: "신진대사", distractors: ["소화", "호흡"] },
      { word: "controlled", meaning: "통제되는", distractors: ["자유로운", "무작위적인"] },
      { word: "weight", meaning: "무게", distractors: ["부피", "밀도"] },
      { word: "enormous", meaning: "거대한", distractors: ["미세한", "보통의"] },
      { word: "atmospheres", meaning: "기압", distractors: ["온도", "습도"] },
    ],
    40: [
      { word: "selfexperimentation", meaning: "자기 실험", distractors: ["집단 실험", "동물 실험"] },
      { word: "conventional", meaning: "전통적인", distractors: ["혁신적인", "실험적인"] },
      { word: "resembles", meaning: "닮다", distractors: ["다르다", "반대되다"] },
      { word: "discovery", meaning: "발견", distractors: ["발명", "창조"] },
      { word: "convincing", meaning: "설득하는", distractors: ["의심하게 하는", "혼란시키는"] },
      { word: "scientists", meaning: "과학자들", distractors: ["철학자들", "역사가들"] },
      { word: "resources", meaning: "자원", distractors: ["결과", "목표"] },
      { word: "hypotheses", meaning: "가설", distractors: ["결론", "증거"] },
      { word: "exploratory", meaning: "탐색적인", distractors: ["확정적인", "반복적인"] },
      { word: "phase", meaning: "단계", distractors: ["결과", "원인"] },
      { word: "procedural", meaning: "절차적인", distractors: ["즉흥적인", "감정적인"] },
      { word: "parameters", meaning: "매개 변수", distractors: ["결과값", "오차범위"] },
      { word: "optimize", meaning: "최적화하다", distractors: ["무시하다", "악화시키다"] },
      { word: "maximize", meaning: "극대화하다", distractors: ["최소화하다", "유지하다"] },
      { word: "validation", meaning: "검증", distractors: ["가설", "반박"] },
    ],
    "41-42": [
      { word: "emergence", meaning: "출현", distractors: ["소멸", "유지"] },
      { word: "datasets", meaning: "데이터셋", distractors: ["알고리즘", "모델"] },
      { word: "visualizing", meaning: "시각화하는", distractors: ["분석하는", "저장하는"] },
      { word: "numerical", meaning: "수치의", distractors: ["질적인", "언어적인"] },
      { word: "statistics", meaning: "통계", distractors: ["수학", "물리"] },
      { word: "forefront", meaning: "최전선", distractors: ["후방", "중심"] },
      { word: "conventions", meaning: "관습", distractors: ["법칙", "규정"] },
      { word: "sophisticated", meaning: "정교한", distractors: ["단순한", "조잡한"] },
      { word: "interpretation", meaning: "해석", distractors: ["측정", "관찰"] },
      { word: "demonstrated", meaning: "증명했다", distractors: ["부정했다", "추측했다"] },
      { word: "incidence", meaning: "발생", distractors: ["소멸", "예방"] },
      { word: "outbreak", meaning: "발병", distractors: ["치료", "예방"] },
      { word: "narrative", meaning: "이야기", distractors: ["데이터", "도표"] },
      { word: "conveyed", meaning: "전달된", distractors: ["차단된", "왜곡된"] },
      { word: "intensifying", meaning: "심화시키는", distractors: ["완화시키는", "유지하는"] },
    ],
  },
};

export default VOCAB_DATA;
